### ISSUE TITLE
Invalid Syntax while running the model with given parameters/weights

### ISSUE THREAD

**Issue by sonubhadana** [kukrishna/pointer-generator-pytorch-allennlp#3]
I'm trying to run the model with given weights but it keeps showing error. I am working on google colab. I have tried removing --cuda-device but error still remains. I have tried searching on stackoverflow but no leads till now.

Here is the [Colab NoteBook](https://colab.research.google.com/drive/1DVfPzb2C33MsTtlKlogXSzQ0hUUTthS5?usp=sharing)

 I'm new to this so may be there's a silly mistake from my side. Please provide your Insight. Thank You.

**Comment by kukrishna** [comment]
Hi! You need to run the "allennlp predict" command in a bash command line. You are running it inside a python notebook, that is why it is not working.

**Comment by sonubhadana** [comment]
> Hi! You need to run the "allennlp predict" command in a bash command line. You are running it inside a python notebook, that is why it is not working.

Thanks for the quick response. Yes, I have installed allennlp and read all the commands. But now I'm getting errors while importing modules as the newer version (2.2.0) does  not support "WordTokenizer". Then I replace it with the new "SpacyTokenizer" but after one another these "module not found" errors are keep poping. Can you give any suggestion ?

**Comment by kukrishna** [comment]
As mentioned in the Readme, you right now the code only supports allennlp version 0.8.5
You can just install that version and it should work then

**Comment by sonubhadana** [comment]
> As mentioned in the Readme, you right now the code only supports allennlp version 0.8.5
> You can just install that version and it should work then

I think, I have managed to provide software requirements (allennlp==0.8.5). Now , it is showing this error.

$ allennlp predict pretrained_model_skeleton_withcoverage.tar.gz --weights-file ../see_etal_weights_with_coverage.th --include-package pointergen --cuda-device 0 --predictor beamsearch sample_datafile.jsonl
2021-04-07 11:12:32,169 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2021-04-07 11:12:33,458 - INFO - pytorch_transformers.modeling_bert - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2021-04-07 11:12:33,469 - INFO - pytorch_transformers.modeling_xlnet - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2021-04-07 11:12:35,310 - INFO - allennlp.models.archival - loading archive file pretrained_model_skeleton_withcoverage.tar.gz
2021-04-07 11:12:35,316 - INFO - allennlp.models.archival - extracting archive file pretrained_model_skeleton_withcoverage.tar.gz to temp dir C:\Users\hp\AppData\Local\Temp\tmpzy22zlct
2021-04-07 11:12:35,339 - WARNING - allennlp.common.params - _jsonnet not loaded, treating C:\Users\hp\AppData\Local\Temp\tmpzy22zlct\config.json as json
Traceback (most recent call last):
  File "c:\users\hp\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hp\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hp\Anaconda3\Scripts\allennlp.exe\__main__.py", line 7, in <module>
  File "c:\users\hp\anaconda3\lib\site-packages\allennlp\run.py", line 18, in run
    main(prog="allennlp")
  File "c:\users\hp\anaconda3\lib\site-packages\allennlp\commands\__init__.py", line 102, in main
    args.func(args)
  File "c:\users\hp\anaconda3\lib\site-packages\allennlp\commands\predict.py", line 214, in _predict
    predictor = _get_predictor(args)
  File "c:\users\hp\anaconda3\lib\site-packages\allennlp\commands\predict.py", line 120, in _get_predictor
    overrides=args.overrides)
  File "c:\users\hp\anaconda3\lib\site-packages\allennlp\models\archival.py", line 214, in load_archive
    config = Params.from_file(os.path.join(serialization_dir, CONFIG_NAME), overrides)
  File "c:\users\hp\anaconda3\lib\site-packages\allennlp\common\params.py", line 477, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
  File "c:\users\hp\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\hp\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\hp\anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 5 (char 130)
2021-04-07 11:12:35,349 - INFO - allennlp.models.archival - removing temporary unarchived model dir at C:\Users\hp\AppData\Local\Temp\tmpzy22zlct

**Comment by kukrishna** [comment]
"2021-04-07 11:12:35,339 - WARNING - allennlp.common.params - _jsonnet not loaded, treating C:\Users\hp\AppData\Local\Temp\tmpzy22zlct\config.json as json"

I think jsonnet is not installed. That would create a problem
